/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import DAO.ExemplarDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import model.Estoque;
import model.Fornecedor;
import model.Produto;
public class Tela extends javax.swing.JFrame {
private int x=0, y=0;

    private int tamanho=0;
ExemplarDAO usando= new ExemplarDAO();
ArrayList <model.Estoque> vetorEstoque = new ArrayList(); 
ArrayList <model.Fornecedor> vetorFornecedores = new ArrayList(); 
JComboBox Combousername2 = new JComboBox();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        Combousername2.addItem("<Selecione Fornecedor>");
      // aqui criamos os iniciais
//    Editora novaEditora = new Editora();
//novaEditora.Editora(1, "Novatec", "São Paulo");   
//vetorEditora.add(novaEditora);
//jComboBox2.addItem(vetorEditora.get(vetorEditora.size()-1).getNome());
// Autor novoAutor = new Autor(); 
// novoAutor.Autor(1, "Deitel & Deitel");
// vetorAutor.add(novoAutor);                         
// jComboBox1.addItem(vetorAutor.get(vetorAutor.size()-1).getNome());
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jText1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Biblioteca");
        setResizable(false);

        jLabel2.setText("Produto");

        jButton1.setText("Tornar Editavel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Fornecedor", "Quantidade"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade de Produtos");

        jText1.setEnabled(false);
        jText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/images (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jButton4.setText("Cadastrar Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cadastrar Forncedor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione o Item>" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Selecione a linha para Remove-la");
        }else{
            DefaultTableModel table= (DefaultTableModel) jTable1.getModel();
                        usando.Remover(jTable1.getSelectedRow());
                        table.removeRow(jTable1.getSelectedRow());
            this.tamanho--;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.x==0){
            jText1.setEnabled(true);
            jComboBox1.setEnabled(true);
            jButton1.setText("Cadastrar");
            this.x++;
        }else{

            DefaultTableModel table= (DefaultTableModel) jTable1.getModel();
            int naoExixteIgual=0;
            if(jText1.getText().equals("") ){
                JOptionPane.showMessageDialog(null, "Todos os itens devem ser validos");
            }else{
                if(!jComboBox1.getSelectedItem().equals("<Selecione o Item>") ){
                try{
                  int qntProdutos=0; 
                     qntProdutos=Integer.valueOf(jText1.getText());
                     
                    for(int y=0; y<table.getRowCount(); y++){
                        //verifica se existe nome igual
                        
                        if (String.valueOf(String.valueOf(jComboBox1.getSelectedItem())).equals(String.valueOf(table.getValueAt(y, 0)))){
                            naoExixteIgual++;
                        }
                    }
                    
                        if(qntProdutos>0 ){
                           if(naoExixteIgual==0){
                      Estoque Index = vetorEstoque.get(jComboBox1.getSelectedIndex()-1);
                                // aqui oque eu cadastrar em produtos
                            usando.InserirEstoque(qntProdutos, Index.getDescricao(), Float.valueOf(Index.getValor()), Index.getNomeFornecedor(), Index.getLocalFornecedor(),Index.getEmailFornecedor());                            
                             
                            //obras.add(novaObra);
                            //Mediador index = obras.get(tamanho);
                            // parei aqui
                            Object[] dados = {String.valueOf(usando.getDescriçãoEstoque(tamanho)),Index.getNomeFornecedor() ,usando.getQntProdutos(tamanho)};                        
                           table.addRow(dados);                          
                            jText1.setText(null);
                            jComboBox1.setSelectedIndex(0);                           
                            this.tamanho++;
JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                           }else{
                             JOptionPane.showMessageDialog(null, "Existem produtos Iguais");  
                           }
                            }else{
                                 JOptionPane.showMessageDialog(null, "Os valores não podem ser negativos");   
                                    }
                    
                    
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "O Numero de exemplares só permite valores inteiros!");
                }
            }else{
                   JOptionPane.showMessageDialog(null, "Seleção invalida, selecione um Autor e uma Editora"); 
                    }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JTextField username = new JTextField();
JTextField username1 = new JTextField();
JTextField username2 = new JTextField();
Object[] message = {
    "Nome", username,
    "Email", username1,
    "Local", username2
};

int option = JOptionPane.showConfirmDialog(null, message, "Cadastro Fornecedor", JOptionPane.OK_CANCEL_OPTION);

if (option == JOptionPane.OK_OPTION) {
    int naoExixteIgual=0;
    if(username.getText().equals("")||username1.getText().equals("") ||username2.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Cadastro Nao Realizado Lacuna em Branco");
         
     }else{
        
                    for(int y=0; y<jComboBox1.getItemCount(); y++){
                        if (String.valueOf(username.getText()).equals(String.valueOf(jComboBox1.getItemAt(y)))){
                            naoExixteIgual++;
                        }
                    }                                          
                        if(naoExixteIgual==0){
                            String Nome=username.getText();
                            String Local=username2.getText();
                            String Email=username1.getText();
                           Fornecedor novoFornecedor = new Fornecedor(); 
                           novoFornecedor.Fornecedor( Nome, Local, Email);
                           vetorFornecedores.add(novoFornecedor);
                           // aqui passamos para o cadastro produto
                           //jComboBox2.addItem(vetorEditora.get(vetorEditora.size()-1).getNome());
                           
                          Combousername2.addItem(Nome);
                        JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso");
                        }else{
                            JOptionPane.showMessageDialog(null, "Cadastro não Realizado opção invalida");
                        }
             
     
    }
} else {
    JOptionPane.showMessageDialog(null, "Cadastro cancelado");
}
        //Aluno_Editora nova = new Aluno_Editora();
//        nova.mostrar(true);
       //JOptionPane.showConfirmDialog(null, nova);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JTextField username = new JTextField();
        JTextField username1 = new JTextField();
        
        Object[] message = {
            "Valor", username,
            "Descrição",username1,
            "Fornecedor", Combousername2
            
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            int naoExixteIgual=0;
            if(username.getText().equals("")||Combousername2.getSelectedItem().equals("<Selecione Fornecedor>")){
                JOptionPane.showMessageDialog(null, "Cadastro Nao Realizado Lacuna em Branco\n ou Fornecedor não Selecionado");

            }else{
                try{
                    float valor= Float.valueOf(username.getText());
                    
                    Fornecedor Index = vetorFornecedores.get(Combousername2.getSelectedIndex()-1);
                    
                        String Nome=username1.getText();

                        Estoque novoProduto = new Estoque();
                        novoProduto.Produto(username1.getText(),valor,Index.getNome(),Index.getLocal(),Index.getEmail());
                        vetorEstoque.add(novoProduto);
                        jComboBox1.addItem(vetorEstoque.get(vetorEstoque.size()-1).getDescricao());
                       JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso");
                    
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "O Código só permite números inteiros!");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro cancelado");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public void rodar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText1;
    // End of variables declaration//GEN-END:variables
}
